#include "stdafx.h"
#include "PluginTable.h"

HRESULT CPluginTable::FinalConstruct()
{
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_WINDOW_SERVICE, SERVICE_DEBUG_FORM_MANAGER, CLSID_DebugFormManager, _T("Debug form manager")));
	RETURN_IF_FAILED(AddPluginInfoRemote(PNAMESP_HOSTFORM, PVIEWTYPE_WINDOW_SERVICE, SERVICE_DEBUG_SESSION_SERVICE, CLSID_DebugSessionService, _T("Debug session service")));
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_WINDOW_SERVICE, SERVICE_VIEW_DEBUG_SESSION_SERVICE, CLSID_ViewDebugEngineService, _T("Debug view service")));
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_WINDOW_SERVICE, SERVICE_PROGRESS_BAR, CLSID_ProgressBarService, _T("Progress bar service")));
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_WINDOW_SERVICE, SERVICE_CONSOLE, CLSID_ConsoleService, _T("Console service")));
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_WINDOW_SERVICE, SERVICE_HANDLE_ERRORS, CLSID_CommandErrorHandlingService, _T("Error handling service")));

	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_COMMAND, COMMAND_CLOSEDUMP, CLSID_CloseDumpCommand, _T("Close dump command")));
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_COMMAND, COMMAND_OPENDUMP, CLSID_OpenDumpCommand, _T("Open dump command")));
	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_COMMAND, COMMAND_SHOWLOG, CLSID_ShowLogCommand, _T("Show log command")));

	RETURN_IF_FAILED(AddPluginInfo(PNAMESP_HOSTFORM, PVIEWTYPE_INPLACE_CONTROL, CONTROL_LOG, CLSID_LogFormView, _T("Log view form")));
	return S_OK;
}
